spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss
    default-property-inclusion: non_null

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: dries-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'SAM' #JWT负载中拿到开头

redis:
  database: dries
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
